<a href="https://colab.research.google.com/github/GraceViesAngel/GraceViesAngel/blob/main/Check_point_2_Grace_Vies_Angel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/AVD/student_spending (1) (1).csv')

# **DATA UNDERSTANDING**

# pemeriksaan struktur data

In [3]:
df

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash
3,3,23,Female,Senior,Computer Science,617,265,4935,652,289,114,223,99,30,163,105,55,Mobile Payment App
4,4,20,Female,Senior,Computer Science,810,522,3887,825,372,168,194,48,71,88,71,104,Credit/Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,22,Female,Senior,Biology,1346,520,3688,969,152,194,151,42,38,252,65,163,Cash
996,996,19,Female,Senior,Biology,1407,560,3380,508,265,52,206,40,98,274,84,135,Mobile Payment App
997,997,20,Male,Junior,Economics,957,393,3497,723,339,139,69,112,46,284,57,28,Mobile Payment App
998,998,22,Non-binary,Senior,Economics,1174,612,3649,543,237,123,200,129,90,190,101,65,Mobile Payment App
999,999,24,Non-binary,Sophomore,Computer Science,541,640,5965,609,270,191,215,139,43,281,88,145,Cash

In [4]:
print('menampilkan beberapa row data')
df.head(10)

menampilkan beberapa row data

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash
3,3,23,Female,Senior,Computer Science,617,265,4935,652,289,114,223,99,30,163,105,55,Mobile Payment App
4,4,20,Female,Senior,Computer Science,810,522,3887,825,372,168,194,48,71,88,71,104,Credit/Debit Card
5,5,25,Non-binary,Sophomore,Computer Science,523,790,3151,413,386,122,131,73,38,234,108,99,Mobile Payment App
6,6,23,Female,Freshman,Engineering,1354,69,4973,812,398,101,213,21,38,157,117,48,Credit/Debit Card
7,7,23,Female,Junior,Economics,631,748,3966,571,269,92,251,37,90,152,56,62,Mobile Payment App
8,8,22,Non-binary,Senior,Computer Science,1402,248,5638,599,354,82,155,123,41,162,172,194,Credit/Debit Card
9,9,18,Female,Junior,Computer Science,1423,74,3977,626,249,117,123,51,74,243,34,196,Mobile Payment App

In [5]:
print('menampilkan 3 baris pertama pada data:')
df.head(3)

menampilkan 3 baris pertama pada data:

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash

In [6]:
print('menampilkan 6 baris terakhir pada data:')
df.tail(6)

menampilkan 6 baris terakhir pada data:

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
994,994,22,Male,Senior,Psychology,764,286,5430,589,387,61,68,46,96,86,46,85,Mobile Payment App
995,995,22,Female,Senior,Biology,1346,520,3688,969,152,194,151,42,38,252,65,163,Cash
996,996,19,Female,Senior,Biology,1407,560,3380,508,265,52,206,40,98,274,84,135,Mobile Payment App
997,997,20,Male,Junior,Economics,957,393,3497,723,339,139,69,112,46,284,57,28,Mobile Payment App
998,998,22,Non-binary,Senior,Economics,1174,612,3649,543,237,123,200,129,90,190,101,65,Mobile Payment App
999,999,24,Non-binary,Sophomore,Computer Science,541,640,5965,609,270,191,215,139,43,281,88,145,Cash

In [7]:
print('menampilkan sedikit informasi tentang dataset:')
df.info()

menampilkan sedikit informasi tentang dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                1000 non-null   int64
 1   age                       1000 non-null   int64
 2   gender                    1000 non-null   object
 3   year_in_school            1000 non-null   object
 4   major                     1000 non-null   object
 5   monthly_income            1000 non-null   int64
 6   financial_aid             1000 non-null   int64
 7   tuition                   1000 non-null   int64
 8   housing                   1000 non-null   int64
 9   food                      1000 non-null   int64
 10  transportation            1000 non-null   int64
 11  books_supplies            1000 non-null   int64
 12  entertainment             1000 non-null   int64
 13  personal_care             1000 non-null   int64
 14  technology                1000 non-null   int64
 15  health_wellness           1000 non-null   int64
 16  miscellaneous             1000 non-null   int64
 17  preferred_payment_method  1000 non-null   object
dtypes: int64(14), object(4)
memory usage: 140.8+ KB

In [8]:
print('menampilkan tipe data dari setiap kolom:')
print(df.dtypes)

menampilkan tipe data dari setiap kolom:
Unnamed: 0                   int64
age                          int64
gender                      object
year_in_school              object
major                       object
monthly_income               int64
financial_aid                int64
tuition                      int64
housing                      int64
food                         int64
transportation               int64
books_supplies               int64
entertainment                int64
personal_care                int64
technology                   int64
health_wellness              int64
miscellaneous                int64
preferred_payment_method    object
dtype: object

In [9]:
print('menampilkan jumlah baris dan kolom pada dataset:')
print(df.shape)

menampilkan jumlah baris dan kolom pada dataset:
(1000, 18)

# statistik deskriptif dan analisis korelasi

In [10]:
df

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash
3,3,23,Female,Senior,Computer Science,617,265,4935,652,289,114,223,99,30,163,105,55,Mobile Payment App
4,4,20,Female,Senior,Computer Science,810,522,3887,825,372,168,194,48,71,88,71,104,Credit/Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,22,Female,Senior,Biology,1346,520,3688,969,152,194,151,42,38,252,65,163,Cash
996,996,19,Female,Senior,Biology,1407,560,3380,508,265,52,206,40,98,274,84,135,Mobile Payment App
997,997,20,Male,Junior,Economics,957,393,3497,723,339,139,69,112,46,284,57,28,Mobile Payment App
998,998,22,Non-binary,Senior,Economics,1174,612,3649,543,237,123,200,129,90,190,101,65,Mobile Payment App
999,999,24,Non-binary,Sophomore,Computer Science,541,640,5965,609,270,191,215,139,43,281,88,145,Cash

In [11]:
print('menampilkan statistik deskriptif dari dataset:')
print(df.describe())

menampilkan statistik deskriptif dari dataset:
        Unnamed: 0          age  monthly_income  financial_aid      tuition  \
count  1000.000000  1000.000000     1000.000000    1000.000000  1000.000000
mean    499.500000    21.675000     1020.650000     504.771000  4520.395000
std     288.819436     2.322664      293.841161     287.092575   860.657944
min       0.000000    18.000000      501.000000       0.000000  3003.000000
25%     249.750000    20.000000      770.750000     261.000000  3779.750000
50%     499.500000    22.000000     1021.000000     513.000000  4547.500000
75%     749.250000    24.000000     1288.250000     751.500000  5285.000000
max     999.000000    25.000000     1500.000000    1000.000000  6000.000000

          housing         food  transportation  books_supplies  entertainment  \
count  1000.00000  1000.000000      1000.00000     1000.000000    1000.000000
mean    696.00600   252.642000       124.63700      174.761000      84.814000
std     171.21862    86.949606        43.55799       72.404518      37.970451
min     401.00000   100.000000        50.00000       50.000000      20.000000
25%     538.75000   175.000000        88.00000      112.000000      54.000000
50%     704.50000   255.000000       123.00000      175.000000      86.000000
75%     837.25000   330.000000       162.25000      238.000000     116.000000
max    1000.00000   400.000000       200.00000      300.000000     150.000000

       personal_care   technology  health_wellness  miscellaneous
count    1000.000000  1000.000000      1000.000000    1000.000000
mean       60.699000   178.304000       114.310000     108.910000
std        22.898007    71.744441        49.591544      52.412221
min        20.000000    50.000000        30.000000      20.000000
25%        41.000000   114.000000        73.000000      63.750000
50%        62.000000   178.000000       115.000000     110.000000
75%        80.000000   241.000000       158.000000     153.000000
max       100.000000   300.000000       200.000000     200.000000

In [12]:
kolom_unik = 'food'
if kolom_unik in df.columns:
  print(f'\nJumlah nilai unik dalam kolom {kolom_unik}:')
  print(df[kolom_unik].value_counts())
else:
  print(f'\nKolom {kolom_unik} tidak ditemukan dalam dataset.')

print('\nmenghitung rata-rata dari setiap kolom:')
print(df.mean(numeric_only=True))

print('\nmenghitung median dari setiap kolom:')
print(df.median(numeric_only=True))

print('\nmenghitung standar deviasi dari setiap kolom:')
print(df.std(numeric_only=True))

print('\nmenghitung korelasi antara setiap pasangan kolom:')
print(df.corr(numeric_only=True))

Jumlah nilai unik dalam kolom food:
food
249    11
375    10
159     9
335     9
269     8
       ..
351     1
117     1
379     1
211     1
244     1
Name: count, Length: 290, dtype: int64

menghitung rata-rata dari setiap kolom:
Unnamed: 0          499.500
age                  21.675
monthly_income     1020.650
financial_aid       504.771
tuition            4520.395
housing             696.006
food                252.642
transportation      124.637
books_supplies      174.761
entertainment        84.814
personal_care        60.699
technology          178.304
health_wellness     114.310
miscellaneous       108.910
dtype: float64

menghitung median dari setiap kolom:
Unnamed: 0          499.5
age                  22.0
monthly_income     1021.0
financial_aid       513.0
tuition            4547.5
housing             704.5
food                255.0
transportation      123.0
books_supplies      175.0
entertainment        86.0
personal_care        62.0
technology          178.0
health_wellness     115.0
miscellaneous       110.0
dtype: float64

menghitung standar deviasi dari setiap kolom:
Unnamed: 0         288.819436
age                  2.322664
monthly_income     293.841161
financial_aid      287.092575
tuition            860.657944
housing            171.218620
food                86.949606
transportation      43.557990
books_supplies      72.404518
entertainment       37.970451
personal_care       22.898007
technology          71.744441
health_wellness     49.591544
miscellaneous       52.412221
dtype: float64

menghitung korelasi antara setiap pasangan kolom:
                 Unnamed: 0       age  monthly_income  financial_aid  \
Unnamed: 0         1.000000 -0.000604        0.009057       0.016293
age               -0.000604  1.000000       -0.015448      -0.022263
monthly_income     0.009057 -0.015448        1.000000       0.037050
financial_aid      0.016293 -0.022263        0.037050       1.000000
tuition           -0.010434  0.037042       -0.000149       0.008536
housing            0.008444  0.023288        0.004471      -0.008199
food               0.001189  0.029906       -0.018521       0.017463
transportation    -0.043872 -0.015375        0.046152       0.017674
books_supplies     0.045192  0.025567        0.003527      -0.048570
entertainment      0.002953  0.060446        0.024454       0.014249
personal_care     -0.019036 -0.052414        0.006842      -0.010427
technology         0.021718  0.005633        0.010084       0.017912
health_wellness    0.003023 -0.025031       -0.032567       0.024430
miscellaneous      0.025077  0.003904       -0.023902      -0.002977

                  tuition   housing      food  transportation  books_supplies  \
Unnamed: 0      -0.010434  0.008444  0.001189       -0.043872        0.045192
age              0.037042  0.023288  0.029906       -0.015375        0.025567
monthly_income  -0.000149  0.004471 -0.018521        0.046152        0.003527
financial_aid    0.008536 -0.008199  0.017463        0.017674       -0.048570
tuition          1.000000 -0.020992 -0.019216        0.036734       -0.009433
housing         -0.020992  1.000000 -0.038335       -0.001975       -0.009936
food            -0.019216 -0.038335  1.000000       -0.003443        0.075485
transportation   0.036734 -0.001975 -0.003443        1.000000        0.012900
books_supplies  -0.009433 -0.009936  0.075485        0.012900        1.000000
entertainment   -0.036925  0.021142  0.012960        0.008505        0.004742
personal_care   -0.039074  0.014577  0.047422        0.048892       -0.037669
technology      -0.007864 -0.017230  0.034033       -0.003910        0.019464
health_wellness  0.010978 -0.006323 -0.003700        0.024824        0.000030
miscellaneous   -0.014844  0.013337  0.005192        0.032136       -0.001294

                 entertainment  personal_care  technology  health_wellness  \
Unnamed: 0            0.002953      -0.019036    0.021718         0.003023
age                   0.060446      -0.052414    0.005633        -0.025031
monthly_income        0.024454       0.006842    0.010084        -0.032567
financial_aid         0.014249      -0.010427    0.017912         0.024430
tuition              -0.036925      -0.039074   -0.007864         0.010978
housing               0.021142       0.014577   -0.017230        -0.006323
food                  0.012960       0.047422    0.034033        -0.003700
transportation        0.008505       0.048892   -0.003910         0.024824
books_supplies        0.004742      -0.037669    0.019464         0.000030
entertainment         1.000000      -0.023282    0.012152        -0.032671
personal_care        -0.023282       1.000000    0.050225         0.004207
technology            0.012152       0.050225    1.000000        -0.025953
health_wellness      -0.032671       0.004207   -0.025953         1.000000
miscellaneous        -0.019109      -0.014038    0.005714        -0.024968

                 miscellaneous
Unnamed: 0            0.025077
age                   0.003904
monthly_income       -0.023902
financial_aid        -0.002977
tuition              -0.014844
housing               0.013337
food                  0.005192
transportation        0.032136
books_supplies       -0.001294
entertainment        -0.019109
personal_care        -0.014038
technology            0.005714
health_wellness      -0.024968
miscellaneous         1.000000

# **DATA PREPARATION**

# Melihat Missing Values

tidak ada nilai yang hilang di dalam dataset "students spending habits

In [15]:
print((df.isna().sum() / len(df)) * 100)

Unnamed: 0                  0.0
age                         0.0
gender                      0.0
year_in_school              0.0
major                       0.0
monthly_income              0.0
financial_aid               0.0
tuition                     0.0
housing                     0.0
food                        0.0
transportation              0.0
books_supplies              0.0
entertainment               0.0
personal_care               0.0
technology                  0.0
health_wellness             0.0
miscellaneous               0.0
preferred_payment_method    0.0
dtype: float64

# Duplicated Values

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, age, gender, year_in_school, major, monthly_income, financial_aid, tuition, housing, food, transportation, books_supplies, entertainment, personal_care, technology, health_wellness, miscellaneous, preferred_payment_method]
Index: []

In [14]:
df = df.drop_duplicates()

In [15]:
df

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash
3,3,23,Female,Senior,Computer Science,617,265,4935,652,289,114,223,99,30,163,105,55,Mobile Payment App
4,4,20,Female,Senior,Computer Science,810,522,3887,825,372,168,194,48,71,88,71,104,Credit/Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,22,Female,Senior,Biology,1346,520,3688,969,152,194,151,42,38,252,65,163,Cash
996,996,19,Female,Senior,Biology,1407,560,3380,508,265,52,206,40,98,274,84,135,Mobile Payment App
997,997,20,Male,Junior,Economics,957,393,3497,723,339,139,69,112,46,284,57,28,Mobile Payment App
998,998,22,Non-binary,Senior,Economics,1174,612,3649,543,237,123,200,129,90,190,101,65,Mobile Payment App
999,999,24,Non-binary,Sophomore,Computer Science,541,640,5965,609,270,191,215,139,43,281,88,145,Cash

# Inconsistens Values

tidak ada nilai yang tidak konsisten di dalam dataset "student spending habits"

In [16]:
df

,Unnamed: 0,age,gender,year_in_school,major,monthly_income,financial_aid,tuition,housing,food,transportation,books_supplies,entertainment,personal_care,technology,health_wellness,miscellaneous,preferred_payment_method
0,0,19,Non-binary,Freshman,Psychology,958,270,5939,709,296,123,188,41,78,134,127,72,Credit/Debit Card
1,1,24,Female,Junior,Economics,1006,875,4908,557,365,85,252,74,92,226,129,68,Credit/Debit Card
2,2,24,Non-binary,Junior,Economics,734,928,3051,666,220,137,99,130,23,239,112,133,Cash
3,3,23,Female,Senior,Computer Science,617,265,4935,652,289,114,223,99,30,163,105,55,Mobile Payment App
4,4,20,Female,Senior,Computer Science,810,522,3887,825,372,168,194,48,71,88,71,104,Credit/Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,22,Female,Senior,Biology,1346,520,3688,969,152,194,151,42,38,252,65,163,Cash
996,996,19,Female,Senior,Biology,1407,560,3380,508,265,52,206,40,98,274,84,135,Mobile Payment App
997,997,20,Male,Junior,Economics,957,393,3497,723,339,139,69,112,46,284,57,28,Mobile Payment App
998,998,22,Non-binary,Senior,Economics,1174,612,3649,543,237,123,200,129,90,190,101,65,Mobile Payment App
999,999,24,Non-binary,Sophomore,Computer Science,541,640,5965,609,270,191,215,139,43,281,88,145,Cash